name: Schedule Tests

on:
  schedule:
    - cron: '0/5 * * * 1-5'

jobs:
  RunTest:
    runs-on: windows-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar Chrome Driver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '88.0.4324.96'
      - run: chromedriver --url-base=/wd/hub &

      - name: Executar Testes
        run: mvn -X test -DfailIfNoTests=false

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting


      - name: Arquivar relatório formatado
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'