name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: windows-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Installer Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Installer Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Installer Chrome Driver
        uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
      - run: chromedriver --url-base=/wd/hub &

      - name: Run Test
        run: mvn test -Dtest-RunCucumber -Dbrowser-chrome-ci

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'